import type { LandingSpec, Section } from '../schemas/landing-spec';

/**
 * Детерминированный TSX-string renderer для handoff (этап 6 ZIP).
 *
 * На этапе 1 это простой mapper component-name → JSX-литерал. Никакого LLM на
 * этом шаге — модель только генерит spec, а сборка TSX из spec'а — чистая
 * функция, чтобы результат был воспроизводим и проверяем.
 */

const INDENT = '  ';

function jsxString(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function literal(value: unknown): string {
  if (value === null) return 'null';
  if (typeof value === 'string') return jsxString(value);
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) {
    return `[${value.map(literal).join(', ')}]`;
  }
  if (value && typeof value === 'object') {
    const entries = Object.entries(value)
      .filter(([, v]) => v !== undefined)
      .map(([k, v]) => `${JSON.stringify(k)}: ${literal(v)}`);
    return `{ ${entries.join(', ')} }`;
  }
  return 'undefined';
}

function renderSection(section: Section): string {
  const tagName = section.component;
  const props = section.props as Record<string, unknown>;
  const attrs = Object.entries(props)
    .filter(([, v]) => v !== undefined)
    .map(([k, v]) => {
      if (typeof v === 'string') return `${INDENT}${k}=${jsxString(v)}`;
      return `${INDENT}${k}={${literal(v)}}`;
    });
  return `<${tagName}\n${attrs.join('\n')}\n/>`;
}

export function renderLandingToTSX(spec: LandingSpec, slug: string): string {
  const usedComponents = new Set<string>();
  const sectionJSX: string[] = [];

  for (const section of spec.sections) {
    usedComponents.add(section.component);
    sectionJSX.push(renderSection(section));
  }

  const imports = [...usedComponents].sort().join(', ');

  return `// AUTO-GENERATED by @buffalo/harness — do not edit by hand
// slug: ${slug}
// pageType: ${spec.pageType}
// goal: ${spec.goal}

import { ${imports} } from '@buffalo/ui/landing';

export const metadata = {
  title: ${jsxString(spec.seo.title)},
  description: ${jsxString(spec.seo.description)},
};

export default function Landing_${slug.replace(/[^a-zA-Z0-9_]/g, '_')}() {
  return (
    <main>
${sectionJSX.map((s) => s.split('\n').map((l) => INDENT + INDENT + l).join('\n')).join('\n\n')}
    </main>
  );
}
`;
}
